### ISSUE TITLE
Feature Request: Get Forex Rates

### ISSUE THREAD

**Issue by kamalogudah** [beamkenya/ex_pesa#76]
**Is your feature request related to a problem? Please describe.**
The Foreign Exchange Rates API Provides Easy Access To The Equity Bank Daily Currency Conversion Rate For Major Currencies [Get Forex Rates](https://developer.jengaapi.io/reference#get-forex-rates)

**Comment by MidigoF** [comment]
Moved to [ex_jenga](https://github.com/beamkenya/ex_jenga/issues/2)
